project 'JGDouYin.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'JGDouYin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JGDouYin

    pod 'AFNetworking'
    pod 'JSONModel'
    pod 'Masonry'
    pod 'SocketRocket'
    pod 'libwebp'

  target 'JGDouYinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JGDouYinUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
